services:
  - type: web
    name: bewiser-smart-advisor
    runtime: python3
    env: python
    plan: free
    # Build settings
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    # Start command
    startCommand: python main_render.py
    # Environment variables
    envVars:
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: PYTHON_VERSION
        value: "3.11"
      - key: RISK_FREE_RATE
        value: "0.065"
      - key: TRADING_DAYS
        value: "252"
    # Health check
    healthCheckPath: /
    # Auto-deploy settings
    autoDeploy: true
    # Branch to deploy from
    branch: main
    # Scaling
    numInstances: 1
    # Disk size
    disk:
      name: bewiser-disk
      mountPath: /opt/render/project/data
      sizeGB: 1
    # Region
    region: oregon
