services:
  - type: web
    name: bewiser-smart-advisor
    runtime: python3
    env: python
    plan: free
    # Build settings
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    # Start command
    startCommand: |
      cd /opt/render/project/src && 
      python -c "
      import sys
      sys.path.insert(0, '/opt/render/project/src')
      from app.main import app
      import uvicorn
      import os
      port = int(os.environ.get('PORT', 10000))
      uvicorn.run(app, host='0.0.0.0', port=port)
      "
    # Environment variables
    envVars:
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: PYTHON_VERSION
        value: "3.11"
      - key: RISK_FREE_RATE
        value: "0.065"
      - key: TRADING_DAYS
        value: "252"
    # Health check
    healthCheckPath: /
    # Auto-deploy settings
    autoDeploy: true
    # Branch to deploy from
    branch: main
    # Scaling
    numInstances: 1
    # Disk size
    disk:
      name: bewiser-disk
      mountPath: /opt/render/project/data
      sizeGB: 1
    # Region
    region: oregon
